// A real-server smoke check; start app_server:app on port 8080 first.
import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||'chrome',headless:true,args:['--enable-unsafe-swiftshader']});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',error=>errors.push(error.message));
 await page.goto('http://127.0.0.1:8080/');await expect(page.locator('#scene canvas')).toBeVisible();
 await page.locator('.assistant summary').click();await page.locator('#assistant-question').fill('How much budget is left?');
 await page.locator('[data-speak]').check();await page.locator('.assistant button[type=submit]').click();
 await expect(page.locator('[data-answer]')).toContainText('100,000');
 await expect(page.locator('.assistant audio')).toBeVisible({timeout:30000});
 await page.locator('[data-speak]').uncheck();await page.locator('.assistant summary').click();
 const debrief=page.waitForResponse(r=>r.url().endsWith('/api/gemini/generate/simulation_debrief'),{timeout:60000});
 await page.locator('#quick-run').click();await page.locator('#run').click();
 await expect(page.locator('#result-status')).toHaveText('100 RUNS',{timeout:15000});
 await expect(page.locator('#scene canvas')).toHaveAttribute('data-playback-speed','1');
 const generated=await (await debrief).json();if(process.argv.includes('--require-gemini'))expect(generated.source).toBe('gemini');
 await page.locator('.assistant summary').click();await expect(page.locator('[data-source]')).toContainText(generated.source==='gemini'?'Generated by Gemini':'Offline explanation');await page.locator('.assistant summary').click();
 await page.locator('#quick-run').click();await page.locator('.sumo-study summary').click();await page.locator('[data-run-sumo]').click();
 await expect(page.locator('[data-sumo-status]')).toContainText('SUMO complete',{timeout:600000});
 await expect(page.locator('#scene canvas')).toHaveAttribute('data-traffic-source','sumo-traci');
 await page.screenshot({path:'test-results/local-connected.png'});
 await page.locator('[data-stop-replay]').click();await expect(page.locator('#scene canvas')).toHaveAttribute('data-traffic-source','illustrative');
 expect(errors).toEqual([]);
 console.log('Local production frontend, grounded textbox, live ElevenLabs audio, worker simulation, and real SUMO replay passed.');
}finally{await browser.close();}
